name              'nuaavee_test'
maintainer        'Anshul Verma'
maintainer_email  'anshul.verma86@gmail.com'
license           'MIT'
description       'This cookbook is used with test-kitchen to test the parent, nuaavee cookbok'
version           '1.0.0'
