driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS'] %>
  availability_zone: us-west-2b
  

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-1404
  driver_plugin: ec2
  driver_config:
    image_id: ami-6ac2a85a
    username: ubuntu
    aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
  - recipe[nuaavee]

suites:
  - name: default
    run_list:
      - recipe[apt]
