language: ruby
bundler_args: --without kitchen_vagrant
rvm:
  - 2.1.1
before_install:
  - echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
  - cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_do.pem
  - ./scripts/install_vagrant.sh
script:
  - bundle exec rake travis --trace
after_script:
  - bundle exec kitchen destroy
  - cat .kitchen/logs/*
branches:
  only:
    - master
    - release
